from django.urls import path
from . import admin_db_proxy, views

urlpatterns = [
    path("",                       views.dashboard,   name="dashboard"),
    path("video/<int:cam_index>/", views.mjpeg,       name="mjpeg"),
    path("api/state/",             views.api_state,   name="api_state"),
    path("api/stats/",             views.api_stats,   name="api_stats"),
    path("api/central/",           views.api_central, name="api_central"),
    path("journeys/",              views.journeys_view, name="journeys"),
    path("api/journeys/",          views.api_journeys, name="api_journeys"),
    path("api/journeys/<str:journey_id>/review/", views.api_journey_review,
                                   name="api_journey_review"),
    path("api/journeys/<str:journey_id>/delete/", views.api_journey_delete,
                                   name="api_journey_delete"),
    path("journeys/<str:journey_id>/capture/<str:modality>/<int:rank>/",
                                   views.api_capture_proxy, name="capture_proxy"),
    path("captures/main-person/<str:person_uid>/",
                                   views.api_main_person_capture_proxy,
                                   name="main_person_capture_proxy"),
    path("persons/",                views.persons_index_view, name="persons_index"),
    path("api/persons/list/",       views.api_persons_list, name="api_persons_list"),
    path("persons/<str:person_uid>/", views.person_detail_view,
                                   name="person_detail"),
    path("api/persons/<str:person_uid>/merge/", views.api_person_merge,
                                   name="api_person_merge"),
    path("api/persons/<str:person_uid>/delete/", views.api_person_delete,
                                   name="api_person_delete"),
    path("detections/",            views.detections_view, name="detections"),
    path("api/detections/<int:event_id>/review/", views.api_event_review,
                                   name="api_event_review"),
    path("api/persons/search/",    views.api_person_search, name="api_person_search"),
    path("api/control/",           views.api_control, name="api_control"),
    path("api/toggle_detection/",  views.api_toggle_detection,
                                   name="api_toggle_detection"),
    path("api/person/<int:person_id>/rename/",
                                   views.api_rename,  name="api_rename"),
    path("logout/",                views.logout_view,  name="logout"),
    path("healthz/",               views.healthz,     name="healthz"),

    path("db-admin/",              views.db_admin_view, name="db_admin"),
    path("api/admin-proxy/database/status",
                                   admin_db_proxy.api_admin_db_status,
                                   name="admin_db_status"),
    path("api/admin-proxy/database/backup",
                                   admin_db_proxy.api_admin_db_backup,
                                   name="admin_db_backup"),
    path("api/admin-proxy/database/reset/preview",
                                   admin_db_proxy.api_admin_db_reset_preview,
                                   name="admin_db_reset_preview"),
    path("api/admin-proxy/database/reset/execute",
                                   admin_db_proxy.api_admin_db_reset_execute,
                                   name="admin_db_reset_execute"),
    path("api/admin-proxy/database/jobs/<str:job_id>",
                                   admin_db_proxy.api_admin_db_job_status,
                                   name="admin_db_job_status"),
]
