# Generated by Django 5.2.17 on 2026-08-06 01:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('source', models.CharField(help_text='/dev/video0 또는 rtsp://... 또는 파일 경로', max_length=300, verbose_name='소스')),
                ('index', models.IntegerField(help_text='/video/<번호> URL 에 쓰임', unique=True, verbose_name='스트림 번호')),
                ('enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
            ],
            options={
                'verbose_name': '카메라',
                'verbose_name_plural': '카메라',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='최초 등장')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='최근 등장')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('confirmed', models.BooleanField(default=False, help_text='사람이 직접 확인한 인물', verbose_name='검수 완료')),
            ],
            options={
                'verbose_name': '인물',
                'verbose_name_plural': '인물',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_conf', models.FloatField(default=0.4, verbose_name='검출 conf')),
                ('reid_threshold', models.FloatField(default=0.55, verbose_name='Re-ID 유사도 컷')),
                ('max_gallery', models.IntegerField(default=5, verbose_name='인물당 갤러리 최대')),
                ('draw_boxes', models.BooleanField(default=True, verbose_name='박스 표시')),
                ('draw_labels', models.BooleanField(default=True, verbose_name='ID 표시')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '런타임 설정',
                'verbose_name_plural': '런타임 설정',
            },
        ),
        migrations.CreateModel(
            name='Tracklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField(help_text='ByteTrack 이 부여한 번호', verbose_name='로컬 ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='종료')),
                ('frames', models.IntegerField(default=0, verbose_name='프레임 수')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.camera', verbose_name='카메라')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracklets', to='tracking.person', verbose_name='인물')),
            ],
            options={
                'verbose_name': '트랙렛',
                'verbose_name_plural': '트랙렛',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crops/%Y%m%d/', verbose_name='크롭')),
                ('embedding', models.BinaryField(blank=True, null=True, verbose_name='임베딩')),
                ('score', models.FloatField(default=0.0, help_text='검출 confidence. 대표 이미지 선정 기준', verbose_name='품질')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시각')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tracking.person', verbose_name='인물')),
                ('tracklet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tracking.tracklet', verbose_name='트랙렛')),
            ],
            options={
                'verbose_name': '스냅샷',
                'verbose_name_plural': '스냅샷',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enter', '진입'), ('exit', '이탈'), ('merge', '병합'), ('split', '분리')], max_length=10, verbose_name='종류')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시각')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.camera', verbose_name='카메라')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.person', verbose_name='인물')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['-at'], name='tracking_ev_at_1f7f71_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tracklet',
            index=models.Index(fields=['camera', 'local_id', 'start_at'], name='tracking_tr_camera__a80ff2_idx'),
        ),
    ]
