# Generated by Django 5.2.17 on 2026-08-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='jetson-multicam-re_id-tracking 의 global_person_id (예: G000001). MQTT 로 들어온 인물만 채워진다.', max_length=64, null=True, unique=True, verbose_name='외부 ID'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(blank=True, help_text='MQTT 로 들어온 인물은 embedding 만 있고 크롭 이미지는 없을 수 있다.', upload_to='crops/%Y%m%d/', verbose_name='크롭'),
        ),
    ]
