# Generated by Django 5.2.17 on 2026-08-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_person_external_id_alter_snapshot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='jetson_cam_a_port',
            field=models.IntegerField(blank=True, default=8000, null=True, verbose_name='Cam A 포트'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='jetson_cam_b_port',
            field=models.IntegerField(blank=True, default=8001, null=True, verbose_name='Cam B 포트'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='jetson_cam_c_port',
            field=models.IntegerField(blank=True, help_text="비워두면 '미가동'으로 표시", null=True, verbose_name='Cam C 포트'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='jetson_cam_d_port',
            field=models.IntegerField(blank=True, default=8002, null=True, verbose_name='Cam D 포트'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='jetson_host',
            field=models.CharField(default='10.10.20.56', max_length=100, verbose_name='Jetson IP'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='jetson_mqtt_port',
            field=models.IntegerField(default=1883, verbose_name='MQTT 포트'),
        ),
    ]
