# Generated by Django 5.2.17 on 2026-08-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_runtimeconfig_jetson_cam_a_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtimeconfig',
            name='jetson_cam_a_port',
        ),
        migrations.RemoveField(
            model_name='runtimeconfig',
            name='jetson_cam_b_port',
        ),
        migrations.RemoveField(
            model_name='runtimeconfig',
            name='jetson_cam_c_port',
        ),
        migrations.RemoveField(
            model_name='runtimeconfig',
            name='jetson_cam_d_port',
        ),
        migrations.AddField(
            model_name='camera',
            name='jetson_host',
            field=models.CharField(blank=True, help_text='이 카메라가 연결된 Jetson 보드 주소. 비워두면 로컬 카메라로 취급.', max_length=100, verbose_name='Jetson IP'),
        ),
        migrations.AddField(
            model_name='camera',
            name='jetson_port',
            field=models.IntegerField(blank=True, default=8000, help_text='그 보드에서 이 카메라 영상을 서빙하는 포트 (예: 8000)', null=True, verbose_name='Jetson 포트'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='source',
            field=models.CharField(blank=True, help_text='로컬 카메라만 씀: /dev/video0 또는 rtsp://... 또는 파일 경로', max_length=300, verbose_name='소스'),
        ),
        migrations.AlterField(
            model_name='runtimeconfig',
            name='jetson_host',
            field=models.CharField(default='10.10.20.56', max_length=100, verbose_name='MQTT 브로커 IP'),
        ),
    ]
