# Generated by Django 5.2.17 on 2026-08-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_runtimeconfig_jetson_cam_a_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='detection_enabled',
            field=models.BooleanField(default=True, verbose_name='감지 활성화'),
        ),
    ]
