# Generated by Django 5.2.17 on 2026-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_runtimeconfig_detection_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='visit_count',
            field=models.IntegerField(default=1, help_text='메인 서버가 관리하는 값을 그대로 받아 저장 (journey_id 개수)', verbose_name='방문 횟수'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='main_server_host',
            field=models.CharField(default='10.10.20.33', max_length=100, verbose_name='메인 서버 IP'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='main_server_port',
            field=models.IntegerField(default=8080, verbose_name='메인 서버 API 포트'),
        ),
        migrations.AlterField(
            model_name='person',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='사람이 직접 확인한 인물 — 메인 서버 데이터가 아니라 이 대시보드에서만 관리하는 로컬 판단(등록/미등록 알림 기준)', verbose_name='검수 완료'),
        ),
        migrations.AlterField(
            model_name='person',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='메인 서버가 배정하는 person_uid (예: P000002). 메인 서버 API로 들어온 인물만 채워진다.', max_length=64, null=True, unique=True, verbose_name='외부 ID(person_uid)'),
        ),
        migrations.AlterField(
            model_name='runtimeconfig',
            name='jetson_host',
            field=models.CharField(default='10.10.20.56', max_length=100, verbose_name='MQTT 브로커 IP (구, 미사용)'),
        ),
        migrations.AlterField(
            model_name='runtimeconfig',
            name='jetson_mqtt_port',
            field=models.IntegerField(default=1883, verbose_name='MQTT 포트 (구, 미사용)'),
        ),
    ]
