# Generated by Django 5.2.17 on 2026-08-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_userproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_id', models.CharField(db_index=True, help_text='예: J000104', max_length=32, unique=True, verbose_name='Journey ID')),
                ('person_status', models.CharField(blank=True, max_length=30, verbose_name='상태')),
                ('route', models.CharField(blank=True, help_text='예: "A -> C -> D"', max_length=120, verbose_name='경로')),
                ('entry_at', models.DateTimeField(blank=True, null=True, verbose_name='진입 시각')),
                ('d_exit_at', models.DateTimeField(blank=True, null=True, verbose_name='D 이탈 시각')),
                ('journey_elapsed_seconds', models.FloatField(blank=True, null=True, verbose_name='소요 시간(초)')),
                ('visit_count', models.IntegerField(blank=True, null=True, verbose_name='방문 횟수(당시 스냅샷)')),
                ('initial_decision', models.CharField(blank=True, max_length=40, verbose_name='초기 판정')),
                ('temporary_person_uid', models.CharField(blank=True, help_text='화면에 최종 Person ID로 노출 금지 — Final Review 전 임시값', max_length=32, verbose_name='임시 UID')),
                ('candidate_person_uid', models.CharField(blank=True, max_length=32, verbose_name='후보 UID')),
                ('final_candidate_person_uid', models.CharField(blank=True, max_length=32, verbose_name='최종 후보 UID')),
                ('canonical_person_uid', models.CharField(blank=True, db_index=True, help_text='Final Review 완료 후 실제 Person ID. Person.external_id 와 일치', max_length=32, verbose_name='확정 UID')),
                ('final_review_result', models.CharField(blank=True, choices=[('NEW', '신규(NEW)'), ('REVISIT', '재방문(REVISIT)'), ('MANUAL_REVIEW_REQUIRED', '검토 필요(MANUAL_REVIEW_REQUIRED)')], db_index=True, max_length=24, verbose_name='최종 판정')),
                ('final_scores', models.JSONField(blank=True, null=True, verbose_name='최종 스코어')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 수신')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 갱신')),
                ('person', models.ForeignKey(blank=True, help_text='canonical_person_uid 가 확정된 후에만 연결된다. MANUAL_REVIEW_REQUIRED 인 동안은 비어있다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='tracking.person', verbose_name='확정 인물')),
            ],
            options={
                'verbose_name': '여정(Journey)',
                'verbose_name_plural': '여정(Journey)',
                'ordering': ['-entry_at', '-created_at'],
            },
        ),
    ]
