# Generated by Django 5.2.17 on 2026-08-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='final_score',
            field=models.FloatField(blank=True, help_text='실API: identity.final_score — 예: 0.850', null=True, verbose_name='최종 스코어(단일)'),
        ),
        migrations.AddField(
            model_name='journey',
            name='journey_status',
            field=models.CharField(blank=True, help_text='여정 자체의 진행 상태 — 예: COMPLETED/EXPIRED/ACTIVE (person_status 와 별개 필드, 실API: journey_status)', max_length=30, verbose_name='여정 상태'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='candidate_person_uid',
            field=models.CharField(blank=True, help_text='실API: identity.initial_candidate_person_uid', max_length=32, verbose_name='후보 UID'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='final_review_result',
            field=models.CharField(blank=True, choices=[('NEW', '신규(NEW)'), ('REVISIT', '재방문(REVISIT)'), ('MANUAL_REVIEW_REQUIRED', '검토 필요(MANUAL_REVIEW_REQUIRED)')], db_index=True, help_text='실API: identity.final_result', max_length=24, verbose_name='최종 판정'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='final_scores',
            field=models.JSONField(blank=True, help_text='실API: identity.final_scores — body/face 모달리티별 세부 점수', null=True, verbose_name='스코어 상세'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='person_status',
            field=models.CharField(blank=True, help_text='이 여정 기준 방문 성격 — 예: RETURNING (실API 필드: person_status)', max_length=30, verbose_name='인물 상태'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='route',
            field=models.CharField(blank=True, help_text='실API는 배열(["A","C","D"])로 오는 걸 "A -> C -> D" 문자열로 합쳐서 저장', max_length=120, verbose_name='경로'),
        ),
    ]
