# Generated by Django 5.2.17 on 2026-08-12 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_journey_final_score_journey_journey_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resolved_person',
            field=models.ForeignKey(blank=True, help_text="'오류' 처리할 때 관리자가 찾아 연결한 실제 인물", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to='tracking.person', verbose_name='실제 인물(오류 처리 시)'),
        ),
        migrations.AddField(
            model_name='event',
            name='review_status',
            field=models.CharField(blank=True, choices=[('confirmed', '확인'), ('error', '오류')], max_length=10, verbose_name='검토 상태'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토 시각'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
    ]
