# Generated by Django 5.2.17 on 2026-08-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_event_resolved_person_event_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='was_unregistered',
            field=models.BooleanField(default=True, verbose_name='찍힌 시점에 미등록자였음'),
        ),
    ]
