# Generated by Django 5.2.17 on 2026-08-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_event_was_unregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='body_images',
            field=models.JSONField(blank=True, null=True, verbose_name='BODY 캡처'),
        ),
        migrations.AddField(
            model_name='journey',
            name='face_images',
            field=models.JSONField(blank=True, null=True, verbose_name='FACE 캡처'),
        ),
    ]
