# Generated by Django 5.2.17 on 2026-08-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_journey_body_images_journey_face_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracking.journey', verbose_name='여정'),
        ),
    ]
