# Generated by Django 5.2.17 on 2026-08-12 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_event_journey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='local_match_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='로컬 매칭 시각'),
        ),
        migrations.AddField(
            model_name='journey',
            name='local_match_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='매칭한 관리자'),
        ),
        migrations.AddField(
            model_name='journey',
            name='local_match_person',
            field=models.ForeignKey(blank=True, help_text='관리자가 사진 보고 직접 지정한 추정 인물(Main 공식 판정과 별개)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_matched_journeys', to='tracking.person', verbose_name='관리자 로컬 매칭'),
        ),
        migrations.AlterField(
            model_name='event',
            name='review_status',
            field=models.CharField(blank=True, choices=[('confirmed', '확인'), ('error', '보류')], max_length=10, verbose_name='검토 상태'),
        ),
    ]
