# Generated by Django 5.2.17 on 2026-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_journey_local_match_at_journey_local_match_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='review_status',
            field=models.CharField(blank=True, choices=[('confirmed', '확인'), ('error', '보류')], max_length=10, verbose_name='검토 상태'),
        ),
    ]
