# Generated by Django 5.2.17 on 2026-08-13 01:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_journey_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_person_uid', models.CharField(blank=True, max_length=32, verbose_name='AI(Main) 제안 후보')),
                ('confirmed_person_uid', models.CharField(blank=True, help_text="비어있으면 '특정 인물 없음(미등록자 확인)'으로 확정한 것", max_length=32, verbose_name='관리자 최종 확정')),
                ('was_correct', models.BooleanField(verbose_name='AI 제안이 맞았는지')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='기록 시각')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to='tracking.event', verbose_name='이벤트')),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to='tracking.journey', verbose_name='여정')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='검토한 관리자')),
            ],
            options={
                'verbose_name': 'AI 매칭 피드백',
                'verbose_name_plural': 'AI 매칭 피드백',
                'ordering': ['-created_at'],
            },
        ),
    ]
